Tutorial for writing EXTRACT output to NWB files
cechava/EXTRACT-public pull request #2
Opened 2021-11-03 16:50 UTC by cechava

This PR creates a tutorial showing how to write output from the EXTRACT pipeline to an NWB file (covering both an existing and a new NWB file). Accordingly, a new helper utility function is created which does the necessary formatting to create a valid NWB file that can be exported.

2021-11-03 16:52 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +%       Otherwise, will try to infer from provided NWB file
I think we default to 0

2021-11-03 16:53 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +%       Otherwise, will try to infer from provided NWB file
I think maybe we should call this "sampling_rate" here, just for clarity.

2021-11-03 16:53 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +    'session_start_time', '2021-01-01 00:00:00', ... %should be specified by user?
Yes, this should be required by the user

2021-11-03 16:53 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +%  options: structure with details necessary for nwb file creation.
It seems a key, value pair syntax might work better here.

2021-11-03 16:54 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +    'session_description', 'EXTRACT output file' ...
These should be settable

2021-11-03 16:56 UTC, cechava commented
@bendichter should this also be a PR on the schnitzer lab's EXTRACT repo or should we first iterate on this among ourselves here?

2021-11-03 16:57 UTC, bendichter commented
@cechava I like how you have been doing it- making the PR internal to iterate a bit and then creating a PR for them

2021-11-03 16:58 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +    'colnames', {'image_mask'}, ...
Does EXTRACT output any metrics for ROIs?

2021-11-03 16:58 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +    );
```suggestion
);
```

2021-11-03 17:00 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +    );
```suggestion
summary_img = types.core.GrayscaleImage('data', output.info.summary_image);
F_img = types.core.GrayscaleImage('data', output.info.F_per_pixel);
max_img = types.core.GrayscaleImage('data', output.info.max_image);
% put images in container
img_container = types.core.Images('description', 'EXTRACT info images');
```

2021-11-03 17:01 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +    'description', 'holds processed calcium imaging data');
```suggestion
    ophys_module = types.core.ProcessingModule('description', 'holds processed calcium imaging data');
```

2021-11-03 17:03 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +%  options: structure with details necessary for nwb file creation.
Look into [inputParser](https://www.mathworks.com/help/matlab/ref/inputparser.html)

2021-11-03 17:03 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +%  options: structure with details necessary for nwb file creation.
or were you doing it this way to try to copy the style of EXTRACT?

2021-11-03 17:17 UTC, cechava commented
Yes, the general style throughout the repo is to use structures as inputs.

On Wed, Nov 3, 2021, 1:03 PM Ben Dichter ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In helper_functions/EXTRACT_output_to_nwb.m
> <https://github.com/cechava/EXTRACT-public/pull/2#discussion_r742155109>:
>
> > @@ -0,0 +1,150 @@
> +function nwb = EXTRACT_output_to_nwb(output, options)
> +% EXTRACT_OUTPUT_TO_NWB writes the data within the EXTRACT output structure
> +% to an NWB file
> +%
> +%  output: EXTRACT output structure
> +%
> +%  options: structure with details necessary for nwb file creation.
>
> or were you doing it this way to try to copy the style of EXTRACT?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cechava/EXTRACT-public/pull/2#discussion_r742155109>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC6IAF4XPBIZMP74RH637N3UKF2QBANCNFSM5HJM6IGQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-03 17:19 UTC, bendichter commented
ok, let's continue copying that style then

2021-11-05 14:28 UTC, bendichter requested changes

2021-11-05 14:28 UTC, bendichter commented on tutorials/NWB_tutorials/write_to_nwb.m
> +options.starting_time = 0; % starting time. Defaults to 0
Let's comment lines that just use default values. Then it will still be clear to users how to set them

2021-11-05 14:28 UTC, bendichter commented
@cechava , this is coming along really nicely!

2021-11-10 02:48 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +            'emission_lambda', NaN ...
should be able to overwrite these

2021-11-10 02:52 UTC, bendichter commented
@cechava this looks great! Let me know when it is ready for review

2021-11-14 19:20 UTC, bendichter commented on tutorials/NWB Tutorials/write_to_NWB.m
> +%% *NWB Extension Setup*
Can you also include similar instructions for downloading and installing MatNWB? I don't think we can assume that users of this tutorial have already done the other tutorial. Alternatively, we could refactor out the MatNWB installation instructions into its own tutorial and refer to it. Either way is fine with me.

2021-11-16 22:20 UTC, cechava commented
@bendichter ready for review

2021-11-16 22:23 UTC, bendichter commented
@cechava can you produce an example output NWB file, run it through pynwb.validate, examine it on HDFView, and examine it using NWBWidgets?

2021-11-22 19:49 UTC, cechava commented
After accounting for the issues documented in matnwb PRs, the produced test files pass validation, look properly formatted with HDFView and can be loaded and examined with nwb2widget.

2021-11-22 22:54 UTC, bendichter commented
@cechava great! Could you provide a link to an example file?

2021-11-22 23:49 UTC, cechava commented
@bendichter sure, here's a [link](https://drive.google.com/file/d/17Cxy0aEg7hm7KcIyYvBP3TEpILnWzERY/view?usp=sharing) to download

2021-11-23 01:20 UTC, bendichter requested changes

2021-11-23 01:20 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +    'data', output.temporal_weights, ...
```suggestion
    'data', output.temporal_weights', ...
```

2021-11-23 01:20 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +    'data', [0 mask_dims(3)-1]' ...
```suggestion
    'data', (0:mask_dims(3)-1)' ...
```

2021-11-23 01:20 UTC, bendichter commented on helper_functions/EXTRACT_output_to_nwb.m
> +    ophys_module.nwbdatainterface.set('DfoverF', output_timeseries);
```suggestion
    ophys_module.nwbdatainterface.set('DfOverF', output_timeseries);
```

2021-11-23 01:21 UTC, bendichter commented
* DfoverF should be DfOverF
* RoiRespondSeries.data is in the wrong orientation

![image](https://user-images.githubusercontent.com/844306/142958032-1519159f-b623-495b-9413-2041b3a0111d.png)

* RoiResponseSeries.rois should be a 20-long vector

2021-11-23 17:57 UTC, cechava commented
double-checking that with latest changes files look good for validation and reading in. Ran into the following error when trying to read-in the file into pynwb
```python
from pynwb import NWBHDF5IO
io = NWBHDF5IO(\
               '/Users/cesar/Repositories/EXTRACT-public/tutorials/NWB Tutorials/EXTRACT_output.nwb',\
               mode='r',\
               load_namespaces=True\
              )
nwb = io.read()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/build/objectmapper.py in construct(self, **kwargs)
   1243         try:
-> 1244             obj = self.__new_container__(cls, builder.source, parent, builder.attributes.get(self.__spec.id_key()),
   1245                                          **kwargs)

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/build/objectmapper.py in __new_container__(self, cls, container_source, parent, object_id, **kwargs)
   1253         obj = cls.__new__(cls, container_source=container_source, parent=parent, object_id=object_id)
-> 1254         obj.__init__(**kwargs)
   1255         return obj

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    581             def func_call(*args, **kwargs):
--> 582                 pargs = _check_args(args, kwargs)
    583                 return func(args[0], **pargs)

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/utils.py in _check_args(args, kwargs)
    574                     msg = '%s: %s' % (func.__qualname__, ', '.join(parse_err))
--> 575                     raise ExceptionType(msg)
    576 

TypeError: PlaneSegmentation.__init__: missing argument 'imaging_plane'

The above exception was the direct cause of the following exception:

ConstructError                            Traceback (most recent call last)
/var/folders/0l/b1c608yd6_1bwmfv3gcpwhyr0000gn/T/ipykernel_66613/4144871343.py in <module>
     12               )
     13 
---> 14 nwb = io.read()

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/backends/hdf5/h5tools.py in read(self, **kwargs)
    496                                        % (self.source, self.__mode))
    497         try:
--> 498             return call_docval_func(super().read, kwargs)
    499         except UnsupportedOperation as e:
    500             if str(e) == 'Cannot build data. There are no values.':  # pragma: no cover

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/utils.py in call_docval_func(func, kwargs)
    422 def call_docval_func(func, kwargs):
    423     fargs, fkwargs = fmt_docval_args(func, kwargs)
--> 424     return func(*fargs, **fkwargs)
    425 
    426 

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    581             def func_call(*args, **kwargs):
    582                 pargs = _check_args(args, kwargs)
--> 583                 return func(args[0], **pargs)
    584         else:
    585             def func_call(*args, **kwargs):

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/backends/io.py in read(self, **kwargs)
     39             # TODO also check that the keys are appropriate. print a better error message
     40             raise UnsupportedOperation('Cannot build data. There are no values.')
---> 41         container = self.__manager.construct(f_builder)
     42         return container
     43 

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    581             def func_call(*args, **kwargs):
    582                 pargs = _check_args(args, kwargs)
--> 583                 return func(args[0], **pargs)
    584         else:
    585             def func_call(*args, **kwargs):

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/build/manager.py in construct(self, **kwargs)
    278                 # we are at the top of the hierarchy,
    279                 # so it must be time to resolve parents
--> 280                 result = self.__type_map.construct(builder, self, None)
    281                 self.__resolve_parents(result)
    282             self.prebuilt(result, builder)

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    581             def func_call(*args, **kwargs):
    582                 pargs = _check_args(args, kwargs)
--> 583                 return func(args[0], **pargs)
    584         else:
    585             def func_call(*args, **kwargs):

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/build/manager.py in construct(self, **kwargs)
    788             raise ValueError('No ObjectMapper found for builder of type %s' % dt)
    789         else:
--> 790             return obj_mapper.construct(builder, build_manager, parent)
    791 
    792     @docval({"name": "container", "type": AbstractContainer, "doc": "the container to convert to a Builder"},

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/utils.py in func_call(*args, **kwargs)
    581             def func_call(*args, **kwargs):
    582                 pargs = _check_args(args, kwargs)
--> 583                 return func(args[0], **pargs)
    584         else:
    585             def func_call(*args, **kwargs):

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/build/objectmapper.py in construct(self, **kwargs)
   1212         cls = manager.get_cls(builder)
   1213         # gather all subspecs
-> 1214         subspecs = self.__get_subspec_values(builder, self.spec, manager)
   1215         # get the constructor argument that each specification corresponds to
   1216         const_args = dict()

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/build/objectmapper.py in __get_subspec_values(self, builder, spec, manager)
   1141                         ret[subspec] = self.__flatten(sub_builder, subspec, manager)
   1142             # now process groups and datasets
-> 1143             self.__get_sub_builders(groups, spec.groups, manager, ret)
   1144             self.__get_sub_builders(datasets, spec.datasets, manager, ret)
   1145         elif isinstance(spec, DatasetSpec):

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/build/objectmapper.py in __get_sub_builders(self, sub_builders, subspecs, manager, ret)
   1192                 if dt is None:
   1193                     # recurse
-> 1194                     ret.update(self.__get_subspec_values(sub_builder, subspec, manager))
   1195                 else:
   1196                     ret[subspec] = manager.construct(sub_builder)

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/build/objectmapper.py in __get_subspec_values(self, builder, spec, manager)
   1141                         ret[subspec] = self.__flatten(sub_builder, subspec, manager)
   1142             # now process groups and datasets
-> 1143             self.__get_sub_builders(groups, spec.groups, manager, ret)
   1144             self.__get_sub_builders(datasets, spec.datasets, manager, ret)
   1145         elif isinstance(spec, DatasetSpec):

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/build/objectmapper.py in __get_sub_builders(self, sub_builders, subspecs, manager, ret)
   1184                 sub_builder = builder_dt.get(dt)
   1185                 if sub_builder is not None:
-> 1186                     sub_builder = self.__flatten(sub_builder, subspec, manager)
   1187                     ret[subspec] = sub_builder
   1188             else:

~/anaconda3/envs/pynwb-dev/lib/python3.9/site-packages/hdmf/build/objectmapper.py in __flatten(self, sub_builder, subspec, manager)
   1197 
   1198     def __flatten(self, sub_builder, subspec, manager):
-> 1199         tmp = [manager.construct(b) for b in sub_builder]
   1200         if len(tmp) == 1 and not subspec.is_many():
   1201             tmp = tmp[0]

~/ana [...]

2021-11-23 19:12 UTC, cechava commented
The issue is resolved when using a SoftLink to the `imaging_plane` in the `PlaneSegmentation` object rather than the object itself.

2021-11-29 18:25 UTC, bendichter commented on tutorials/NWB Tutorials/write_to_NWB.m
> +options.imaging_plane.name = 'imaging_plane'; %Defaults to ImagingPlane
```suggestion
%options.imaging_plane.name = 'imaging_plane'; %Defaults to ImagingPlane
```

2021-11-29 18:32 UTC, bendichter commented on tutorials/NWB Tutorials/write_to_NWB.m
> +%the EXTRACT pipeline.
```suggestion
% NOTE: This tutorial assumes you have an output variable in your workspace
% after running the EXTRACT pipeline. See the read_in_NWB.m tutorial  in the 
% same folder or the '1. Starting code' tutorial for details on how to run
% the EXTRACT pipeline.
```

2021-11-29 23:34 UTC, cechava commented
merged to main EXTRACT-public repo

2021-11-29 23:35 UTC, cechava commented
merged to main EXTRACT-public repo

2021-11-29 23:35 UTC, closed without merging